blank_issues_enabled: false
contact_links:
  - name: Getting Started
    url: https://manikandan-kyyba.github.io/k-rapid/getting-started.html
    about: Read how to get started with k-rapid.
  - name: Documentation
    url: https://manikandan-kyyba.github.io/k-rapid/index.html
    about: Read the official documentation.
