blank_issues_enabled: false
contact_links:
  - name: Getting Started
    url: https://manikandan-kyyba.github.io/react-native-kyyba/getting-started.html
    about: Read how to get started with react-native-kyba.
  - name: Documentation
    url: https://manikandan-kyyba.github.io/react-native-kyyba/index.html
    about: Read the official documentation.
