name: Check versions
on:
  issues:
    types: [opened, edited]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: react-navigation/check-versions-action@v1.0.0
        with:
          github-token: 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
          required-packages: |
            react-native
            react-native-kyba
            react-native-vector-icons
          optional-packages: |
            expo
            npm
            yarn
